---
blank_issues_enabled: false
contact_links:
  - name: protoc-gen-temporal Community Support
    url: https://github.com/lucasclerissepro/protoc-gen-temporal/discussions
    about: Please ask and answer questions here.
