package golang

const WorkflowTpl = `// Code generated by protoc-gen-temporal. DO NOT EDIT.
// source: {{ .InputPath }}

package test

import (
	"go.temporal.io/sdk/workflow"
	"go.temporal.io/sdk/activity"
)

`



